### PR TITLE
[security] Fix a panic from an unchecked string slice.

### PR DESCRIPTION
**Pull request by nmathewson**
When slicing a string, you get a panic if you do so at any point
other than at a character boundary.  This happened in the
implementation of UTCTime parsing.

This bug was introduced in bc156c36d76d91b77cdf8f1f231e2c554ea0e454,
and appears to affect only version 0.6.0.

I've tried using the clippy::string_slice lint to confirm that there
are not any other string slices in this code.

Fixes bug #27.  Found via fuzzing.

### CODE REVIEW

**Comment by nmathewson** [comment]
I fuzzed this branch for a couple more hours, but no further problems turned up.

**Comment by nmathewson** [comment]
By the way, please let me know if you'd like me to open a RUSTSEC advisory for this, or if you'd rather do it yourself?

**Comment by acw** [comment]
Hey, you found it, I think you should get the credit for the advisory :)

I'll put another comment in here with the new version number (which will almost certainly be 0.6.1, but ...).

**Comment by acw** [comment]
Published upstream as 0.6.1!

**Comment by Shnatsel** [comment]
Hello, RustSec maintainer here. Thanks for acting on the issue so quickly!

I'd like to confirm with @acw that you want to treat panics in this crate as security issues. It's reasonable for a format decoder that handles untrusted data to treat panics as a security issue; but we don't want to have an inconsistent coverage where some panics in the crate are tracked but others are not.

**Comment by acw** [comment]
After some thinking: yes, I think that makes sense. Especially for something like ASN.1, being able to crash a process remotely could be a significant safety or security concern.

**Comment by Shnatsel** [comment]
I'm merging the advisory then. Thanks again!

**Pull request merged**
